version: '3.8'

services:
  sentinelops-api:
    container_name: sentinelops
    build:
      context: ..

    ports:
      - "5000:5000"
    volumes:
      - ../logs:/app/logs
    restart: unless-stopped
